--Tracker:AddLayouts("layouts/settings_popup.json")
--Tracker:AddLayouts("layouts/items.json")
Tracker:AddLayouts("layouts/tabs.json")
Tracker:AddLayouts("layouts/tracker.json")
Tracker:AddLayouts("layouts/01SunriseSpring_layout.json")
Tracker:AddLayouts("layouts/02MiddayGardens_layout.json")
Tracker:AddLayouts("layouts/03EveningLake_layout.json")
Tracker:AddLayouts("layouts/04MidnightMountain_layout.json")

print("Layout 01 status: " .. tostring(Tracker:FindLayout("01SunriseSpring_layout")))
print("Layout 02 status: " .. tostring(Tracker:FindLayout("02MiddayGardens_layout")))
print("Layout 03 status: " .. tostring(Tracker:FindLayout("03EveningLake_layout")))
print("Layout 04 status: " .. tostring(Tracker:FindLayout("04MidnightMountain_layout")))